### ISSUE TITLE
Support layered family tree representations with parents on the same level

### ISSUE THREAD

**Issue by arthurshir** [nabil6391/graphview#112]
### Ex. BuchheimWalkerAlgorithm
Currently, multiple parents results in overlapping nodes.

Ex:
```
graph.addEdge(node1, node2);
graph.addEdge(node3, node2);
```

Results in something like this
<img width="87" alt="Screenshot 2023-09-06 at 6 32 24 PM" src="https://github.com/nabil6391/graphview/assets/38710729/5b3493fa-3b19-4a43-a548-a6f46c668a23">

### Ex: SugiyamaAlgorithm

Current Behavior:
<img width="351" alt="Screenshot 2023-09-06 at 6 39 16 PM" src="https://github.com/nabil6391/graphview/assets/38710729/409999cf-c4f7-44b3-bb74-c8e0945dad05">

**Comment by arthurshir** [comment]
Closing. Workaround is to do a bottom up configuration and to add a dummy node to represent bottom level siblings

**Comment by devenderTY** [comment]
"Closing. Workaround is to do a bottom up configuration and to add a dummy node to represent bottom level siblings"

@arthurshir  can you please show the code , how you achieved it?

**Comment by NALAWALAMURTUZA** [comment]
@arthurshir please share code.

**Comment by arthurshir** [comment]
Thanks for following up. My workaround didn't work unfortunately
