### ISSUE TITLE
Add edge without shifting other nodes?

### ISSUE THREAD

**Issue by waj334** [nabil6391/graphview#12]
I'm implementing a drag and drop interface and I'm noticing that nodes tend to shift positions as edges are created. Is there a way to fix the position of the existing node when using it to create a new edge?

Great library btw!

![screen-20201024-140652](https://user-images.githubusercontent.com/23425976/97091692-4992c300-1603-11eb-806a-80a3b50fae5b.gif)

**Comment by nabil6391** [comment]
Thanks @waj334 

Its an interesting concept, would be able to give me a working gist so that I can test and correct the implementation

**Comment by waj334** [comment]
I doubt you'd need the whole implementation of my drag and drop, so you could probably replicate the behavior by just adding a node from the onDragStart function on a Draggable and removing it in onDragCompleted.

I think for my use case though, I want to not have the nodes automatically positioned so that I can allow the user to place them where ever they want. I assume I just need a custom Layout that just does nothing?

**Comment by waj334** [comment]
`class DumbGraphAlgorithm implements Layout {
  DumbGraphAlgorithm({this.renderer}) {
    renderer = renderer ?? ArrowEdgeRenderer();
  }
  
  @override
  EdgeRenderer renderer;

  @override
  Size run(Graph graph, double shiftX, double shiftY) {
    return calculateGraphSize(graph);
  }

  @override
  void setFocusedNode(Node node) {
    //Do nothing
  }

  Size calculateGraphSize(Graph graph) {
    var left = double.infinity;
    var top = double.infinity;
    var right = double.negativeInfinity;
    var bottom = double.negativeInfinity;

    graph.nodes.forEach((node) {
      left = min(left, node.x);
      top = min(top, node.y);
      right = max(right, node.x + node.width);
      bottom = max(bottom, node.y + node.height);
    });

    return Size(right - left, bottom - top);
  }
}`

**Comment by nabil6391** [comment]
Nice
