### ISSUE TITLE
Making graphview work with existing flutter directed/weighted graph data structures

### ISSUE THREAD

**Issue by matriculus** [nabil6391/graphview#121]
I have seen the issue of every flutter graphview functionality comes with its own graph data structure and they all lack in crucial functionalities.

GraphView is one of the best I have seen. But rather having a custom graph data structure, if GraphView supports existing directed graph data structures in flutter like `https://pub.dev/packages/directed_graph`, and add functionalities of weighted edges with arrow thickness, it will be of great help.

I can join the party for this implementation, I know it is a big task. I can put my hand if someone is interested.

**Comment by nabil6391** [comment]
I think its quite easy to map from one data structure to another, like how I shown to convert from json to the Graph Nodes. I am more curious if the above packages have implementations for layouting the nodes, which is primarily what this package is focused on.

**Comment by matriculus** [comment]
Got it. I realised it when trying to replace the graph last night. Makes sense. Especially updating the layout needs functionality which cannot be implemented in standard graph data structures.

Is there a way to implement edge thickness and edge weight here? Just curious.
