### ISSUE TITLE
Paint is not always complete

### ISSUE THREAD

**Issue by jrheisler** [nabil6391/graphview#19]
I noticed with some graphs when you zoom you lose part of the painting:

This is with graphview: ^0.6.5
Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19041.685], locale en-US)

![Screenshot (231)](https://user-images.githubusercontent.com/15838441/103480239-fd44cb80-4d87-11eb-8b47-b2f6446c02a9.png)

![Screenshot (230)](https://user-images.githubusercontent.com/15838441/103480242-033aac80-4d88-11eb-8bb8-24fd07fc6b9c.png)

**Comment by jrheisler** [comment]
Fyi, this only happens when you pan and zoom are allowed.

**Comment by nabil6391** [comment]
Ok will have a look

**Comment by mikeborodin** [comment]
Any updates or fixes for this issue? I have similar black artifacts when zoomin in. 
![image](https://user-images.githubusercontent.com/7038472/104932607-1a90b100-59a8-11eb-8829-bd24d55ecd1e.png)

**Comment by nabil6391** [comment]
I always had an issue with the Zooming of the libary. Did not come to the reason or ways to solve it.

Was this ok in earlier versions of graphview?

**Comment by jrheisler** [comment]
Hopefully Mike knows, as I too have never had much luck with zooming. I have instead gone with changing the size of the nodes and the space between them.

**Comment by nabil6391** [comment]
I am interested to help if someone can put in a working code for me to test out.

**Comment by jrheisler** [comment]
It might even have to do with the shadowing on the container that is the node. I have taken to using a slider and resizing the container/node with the slider. It seems like the InteractiveViewer is the issue.

**Comment by nabil6391** [comment]
I am closing this ticket. Hoping this is not relevant anymore
