### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by Nolence** [nabil6391/graphview#21]
Hi !

I like this package and was wondering if there's plans for supporting null safety. I can also start a PR if you'd like.

Thanks

**Comment by nabil6391** [comment]
Yes you can start, Let me know how I can help

**Comment by MateusAmin** [comment]
The migration tool is gets this project most of the way there from ~120 to ~6 errors. However, there are design choices to be made which is easier to do in the migration tool itself:

https://dart.dev/null-safety/migration-guide

**Comment by Nolence** [comment]
Oh! My apologies as well. Meant to do this but must've forgot I said this and got distracted with other packages. If anyone would like to take this over, please feel free to

**Comment by MateusAmin** [comment]
I made a working PR if anyone needs an immediate workaround. But someone with more time should probably take a stab at it.

**Comment by nabil6391** [comment]
NullSafety version has been released guys, thanks for the wait
Version: 1.0.0-nullsafety.1
