### ISSUE TITLE
How to center tree on the canvas ?

### ISSUE THREAD

**Issue by olzii** [nabil6391/graphview#24]
I am using this plugin to display Family tree. And it does not center when displayed.
![Screenshot_20210119-202838](https://user-images.githubusercontent.com/5012289/105035744-746fa480-5a96-11eb-919f-dce5bf164396.jpg)

I need to center horizontally like this on small tree and big family tree when first displayed :
![Screenshot_20210119-203319](https://user-images.githubusercontent.com/5012289/105035757-7a658580-5a96-11eb-9334-344c873694c7.jpg)

How to do it ?

**Comment by nabil6391** [comment]
Hm it should have worked, can you give me a short sample to show what you did?

**Comment by olzii** [comment]
`Widget tree_view_graph(FTreeHomeController model){
    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      mainAxisAlignment: MainAxisAlignment.center,
      mainAxisSize: MainAxisSize.max,
      children: [
        Expanded(
          child: Container(
            alignment: Alignment.center,
            decoration: BoxDecoration(),
            child: InteractiveViewer(
              constrained: false,
              scaleEnabled: true,
              boundaryMargin: EdgeInsets.all(100),
              minScale: 0.000000000001,
              maxScale: 5.6,
              child: GraphView(
                graph: model.graph,
                algorithm: BuchheimWalkerAlgorithm(model.builder, renderer),
                paint: Paint()
                  ..color = Colors.green
                  ..strokeWidth = 1
                  ..style = PaintingStyle.stroke,
              ),
            ),
          ),
        ),
      ],
    );
  }`

**Comment by VengaiMovan** [comment]
Hi @olzii ,
    In treeview it shows 
**RenderPointerListener does not meet its constraints.
**
any idea?

**Comment by nabil6391** [comment]
@olzii I tried your code, still in my case its showing in the middle. Try to see if there are no unconnected nodes. 
Also see if the first node is the first one you are adding.

**Comment by sjimbonator** [comment]
@olzii if you set constrained to true on your InteractiveViewer and wrap its child with an OverflowBox with Alignment.center it will center the tree. This way you can also put your InteractiveViewer directly on the body of your scaffold without the Column and Container etc.

Example:
```dart
  @override
  Widget build(BuildContext context) {
    return InteractiveViewer(
      minScale: 0.35,
      maxScale: 1,
      boundaryMargin: EdgeInsets.all(double.infinity),
      child: OverflowBox(
        alignment: Alignment.center,
        minWidth: 0.0,
        minHeight: 0.0,
        maxWidth: double.infinity,
        maxHeight: double.infinity,
        child: GraphView(
          algorithm: BuchheimWalkerAlgorithm(
            builder,
            TreeEdgeRenderer(builder),
          ),
          graph: graph,
          paint: Paint()
            ..color = Theme.of(context).primaryIconTheme.color
            ..strokeWidth = 1
            ..style = PaintingStyle.stroke,
        ),
      ),
    );
  }
```

This is because if you set constrained to false on InteractiveViewer Flutter will wrap the Interactive viewer with:
```dart
    if (!widget.constrained) {
      child = OverflowBox(
        alignment: Alignment.topLeft,
        minWidth: 0.0,
        minHeight: 0.0,
        maxWidth: double.infinity,
        maxHeight: double.infinity,
        child: child,
      );
    }
``` 
So by doing this wrapping yourself and changing the alignment you can get the behaviour you want.

**Comment by olzii** [comment]
@sjimbonator It is working now, thank you very much.

**Comment by xiaobingcaicai** [comment]
> @olzii if you set constrained to true on your InteractiveViewer and wrap its child with an OverflowBox with Alignment.center it will center the tree. This way you can also put your InteractiveViewer directly on the body of your scaffold without the Column and Container etc.
> 
> Example:
> 
> ```dart
>   @override
>   Widget build(BuildContext context) {
>     return InteractiveViewer(
>       minScale: 0.35,
>       maxScale: 1,
>       boundaryMargin: EdgeInsets.all(double.infinity),
>       child: OverflowBox(
>         alignment: Alignment.center,
>         minWidth: 0.0,
>         minHeight: 0.0,
>         maxWidth: double.infinity,
>         maxHeight: double.infinity,
>         child: GraphView(
>           algorithm: BuchheimWalkerAlgorithm(
>             builder,
>             TreeEdgeRenderer(builder),
>           ),
>           graph: graph,
>           paint: Paint()
>             ..color = Theme.of(context).primaryIconTheme.color
>             ..strokeWidth = 1
>             ..style = PaintingStyle.stroke,
>         ),
>       ),
>     );
>   }
> ```
> 
> This is because if you set constrained to false on InteractiveViewer Flutter will wrap the Interactive viewer with:
> 
> ```dart
>     if (!widget.constrained) {
>       child = OverflowBox(
>         alignment: Alignment.topLeft,
>         minWidth: 0.0,
>         minHeight: 0.0,
>         maxWidth: double.infinity,
>         maxHeight: double.infinity,
>         child: child,
>       );
>     }
> ```
> 
> So by doing this wrapping yourself and changing the alignment you can get the behaviour you want.

but this will not show all the tree node widget if i have much node,how to resolve it?

**Comment by saiypafateme** [comment]
hello,
How can we implement the opening and closing of nodes in package?

**Comment by dev1942** [comment]
Hey!, I wanted to ask if we could make tree like the normal Family tree in which there are two parents of the node. and the parents and the children are on different depth levels.

**Comment by sumiran1601-cp** [comment]
Expanded(
                        child: Padding(
                          padding: const EdgeInsets.all(24.0),
                          child: InteractiveViewer(
                            minScale: 1,
                            maxScale: 2,

                            // boundaryMargin: EdgeInsets.only(top: 100, bottom: 100),
                            constrained: true,
                            boundaryMargin:
                                const EdgeInsets.only(top: 48, bottom: 48),
                            // minScale: 0.01,
                            // maxScale: 5.6,
                            child: OverflowBox(
                              alignment: Alignment.center,
                              minWidth: 0.0,
                              minHeight: 0.0,
                              maxWidth: double.infinity,
                              maxHeight: double.infinity,
                            child: GraphView(
                              key: provider.graphKey,
                              graph: provider.graph,
                              algorithm: BuchheimWalkerAlgorithm(
                                  builder, TreeEdgeRenderer(builder)),
                              paint: Paint()
                                ..color = Colors.green
                                ..strokeWidth = 1
                                ..style = PaintingStyle.stroke,
                              builder: (Node node) {
                                var nodeData =
                                    node.key?.value as Map<String, dynamic>;
                                if (nodeData['id'] == -1) {
                                  return _initialContainer(provider);
                                } else {
                                  return _buildStepContainer(
                                      nodeData['value'], provider);
                                }
                              },
                            ),
                            ),
                          ),
                        ),
                      ), Not working content is not fully visible and by doing boundary margin double.infinity it is taking too much space even the content is small
