### ISSUE TITLE
RenderPointerListener does not meet its constraints what is the error?

### ISSUE THREAD

**Issue by VengaiMovan** [nabil6391/graphview#25]
I have take the treeview example from git, after run it shows this error.

**Comment by nabil6391** [comment]
Try this:

`
 Expanded(
          child: InteractiveViewer(
              constrained: false,
              boundaryMargin: EdgeInsets.all(100),
              minScale: 0.01,
              maxScale: 5.6,
              child: GraphView(
                graph: graph,
                algorithm: BuchheimWalkerAlgorithm(builder, TreeEdgeRenderer(builder)),
                paint: Paint()
                  ..color = Colors.green
                  ..strokeWidth = 1
                  ..style = PaintingStyle.stroke,
              )),
        ),
`
