### ISSUE TITLE
Nodes and edges not rendering correctly when generated dynamically.

### ISSUE THREAD

**Issue by DroidSU** [nabil6391/graphview#28]
Hello, thanks for this great package. 
Just a little query though. The package works great when the nodes and edges are created statically, but the edges are created one over another when the nodes and edges are created inside a for loop. Maybe I am missing something, can you please demonstrate how to create the nodes and edges dynamically and update the documentation.  Will be of so much help. Thanks.

**Comment by nabil6391** [comment]
Hi, which algorithm are you using?

**Comment by DroidSU** [comment]
> Hi, which algorithm are you using?

I am using the BuchheimWalkerAlgorithm algorithm with TreeEdgeRenderer.

**Comment by nabil6391** [comment]
@DroidSU did u fix the issue?

**Comment by DroidSU** [comment]
> @DroidSU did u fix the issue?

No Sir not yet.
