### ISSUE TITLE
Handle disconnected nodes

### ISSUE THREAD

**Issue by roberteverman** [nabil6391/graphview#3]
Is there a way to handle for nodes that aren't connected to the main branch? I guess I'm asking whether it is possible to show two disconnected networks in the same interactive viewer. Currently if not all nodes are connected they are drawn on top of each other.

**Comment by nabil6391** [comment]
Which graph algorithm did you try?

**Comment by roberteverman** [comment]
I'm using the BuchheimWalkerAlgorithm but I didn't think to try and use the others.

**Comment by roberteverman** [comment]
Looks like it works with the SugiyamaAlgorithm which is good enough for my purposes. But might be something you want to look at in the future.

**Comment by roberteverman** [comment]
The FruchtermanReingoldAlgorithm allows it as well but it sometimes throws the disconnected network way out away from the main network.

**Comment by nabil6391** [comment]
Good to know. The feature would not be available for BuchheimWalker which is for tree layout mostly. So I am closing this
