### ISSUE TITLE
import issues

### ISSUE THREAD

**Issue by profiteroles** [nabil6391/graphview#30]
First of thank you very much for putting effort and sharing with us. I may not be the best tester but I found some issues with importing stuff over. I have got the dependency of graphview: ^0.6.7

so there are some screenshots may help you to see what I mean. all of them giving error except one.

btw this code straight from your example section on pub.dev
![1](https://user-images.githubusercontent.com/64768508/109166318-8c35f900-77b7-11eb-8841-8f31aa8323fb.png)
![2](https://user-images.githubusercontent.com/64768508/109166327-8e985300-77b7-11eb-95f4-6c62bc7317cc.png)
![3](https://user-images.githubusercontent.com/64768508/109166334-90621680-77b7-11eb-9df7-3ba4bb0c020a.png)

**Comment by nabil6391** [comment]
@Frezyx , please all dependcedies and import again. Some of the imports are using the one from the example.

**Comment by profiteroles** [comment]
@nabil6391 Thank you Nabil. I was also wondering if I could change the algorithm to AVL balance tree by any any chance, using exiting library of graphview?

**Comment by nabil6391** [comment]
Dont think so, sorry
