### ISSUE TITLE
Upgrade to 1.26.0-17.8.pre

### ISSUE THREAD

**Issue by jrheisler** [nabil6391/graphview#31]
Since upgrading to beta 1.26.0-17.8.pre this last weekend I've noticed, not always, and some what randomly the following error in the terminal when calling GraphView with the SugiyamaAlgorithm. It doesn't seem to effect the running app:

======== Exception caught by rendering library =====================================================
The following IndexError was thrown during performLayout():
RangeError (index): Index out of range: index should be less than 1: 1

The relevant error-causing widget was: 
  GraphView$ file:///C:/source/AndroidStudioProjects/orpheus/lib/screens/parking_lot/forced_direction_view.dart:65:14
When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 581:7             _get]
packages/graphview/layered/SugiyamaAlgorithm.dart 564:49                                                                   verticalAlignment
packages/graphview/layered/SugiyamaAlgorithm.dart 375:9                                                                    assignX
packages/graphview/layered/SugiyamaAlgorithm.dart 329:5                                                                    coordinateAssignment
...
The following RenderObject was being processed when the exception was fired: RenderCustomLayoutBox#68954 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(unconstrained)
...  size: Size(1125.0, 232.5)
...  graph: Instance of 'Graph'
...  algorithm: Instance of 'SugiyamaAlgorithm'
...  paint: Instance of 'CkPaint'
RenderObject: RenderCustomLayoutBox#68954 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
  parentData: <none> (can use size)
  constraints: BoxConstraints(unconstrained)
  size: Size(1125.0, 232.5)
  graph: Instance of 'Graph'
  algorithm: Instance of 'SugiyamaAlgorithm'
  paint: Instance of 'CkPaint'
...  child 1: RenderSemanticsGestureHandler#6614d relayoutBoundary=up3
...    parentData: offset=Offset(10.0, 62.5) (can use size)
...    constraints: BoxConstraints(unconstrained)
...    size: Size(30.0, 30.0)
...    gestures: tap
...    child: RenderPointerListener#dd099 relayoutBoundary=up4
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(30.0, 30.0)
...      behavior: deferToChild
...      listeners: down
...      child: RenderConstrainedBox#3bbfd relayoutBoundary=up5
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(unconstrained)
...        size: Size(30.0, 30.0)
...        additionalConstraints: BoxConstraints(w=30.0, h=30.0)
...        child: RenderDecoratedBox#1958c
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=30.0, h=30.0)
...          size: Size(30.0, 30.0)
...          decoration: BoxDecoration
...            color: Color(0xffffffff)
...            image: DecorationImage(AssetImage(bundle: null, name: "assets/process.png"), BoxFit.fill, Alignment.center, scale: 1)
...            border: Border.all(BorderSide(Color(0xff000000), 1.0, BorderStyle.solid))
...            borderRadius: BorderRadius.circular(5.0)
...            boxShadow: BoxShadow(Color(0xff000000), Offset(4.0, 4.0), 4.0, 0.0)
...          configuration: ImageConfiguration(bundle: PlatformAssetBundle#589c7(), devicePixelRatio: 1.0, locale: en_US, textDirection: TextDirection.ltr, platform: windows)
...  child 2: RenderSemanticsGestureHandler#a7315 relayoutBoundary=up3
...    parentData: offset=Offset(115.0, 62.5) (can use size)
...    constraints: BoxConstraints(unconstrained)
...    size: Size(30.0, 30.0)
...    gestures: tap
...    child: RenderPointerListener#f1907 relayoutBoundary=up4
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(30.0, 30.0)
...      behavior: deferToChild
...      listeners: down
...      child: RenderConstrainedBox#3bd74 relayoutBoundary=up5
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(unconstrained)
...        size: Size(30.0, 30.0)
...        additionalConstraints: BoxConstraints(w=30.0, h=30.0)
...        child: RenderDecoratedBox#a9207
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=30.0, h=30.0)
...          size: Size(30.0, 30.0)
...          decoration: BoxDecoration
...            color: Color(0xffffffff)
...            image: DecorationImage(AssetImage(bundle: null, name: "assets/process.png"), BoxFit.fill, Alignment.center, scale: 1)
...            border: Border.all(BorderSide(Color(0xff000000), 1.0, BorderStyle.solid))
...            borderRadius: BorderRadius.circular(5.0)
...            boxShadow: BoxShadow(Color(0xff000000), Offset(4.0, 4.0), 4.0, 0.0)
...          configuration: ImageConfiguration(bundle: PlatformAssetBundle#589c7(), devicePixelRatio: 1.0, locale: en_US, textDirection: TextDirection.ltr, platform: windows)
...  child 3: RenderSemanticsGestureHandler#7319b relayoutBoundary=up3
...    parentData: offset=Offset(220.0, 62.5) (can use size)
...    constraints: BoxConstraints(unconstrained)
...    size: Size(30.0, 30.0)
...    gestures: tap
...    child: RenderPointerListener#42246 relayoutBoundary=up4
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(unconstrained)
...      size: Size(30.0, 30.0)
...      behavior: deferToChild
...      listeners: down
...      child: RenderConstrainedBox#5b69f relayoutBoundary=up5
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(unconstrained)
...        size: Size(30.0, 30.0)
...        additionalConstraints: BoxConstraints(w=30.0, h=30.0)
...        child: RenderDecoratedBox#c1f06
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=30.0, h=30.0)
...          size: Size(30.0, 30.0)
...          decoration: BoxDecoration
...            color: MaterialColor(primary value: Color(0xffffeb3b))
...            image: DecorationImage(AssetImage(bundle: null, name: "assets/process.png"), BoxFit.fill, Alignment.center, scale: 1)
...            border: Border.all(BorderSide(Color(0xff000000), 1.0, BorderStyle.solid))
...            borderRadius: BorderRadius.circular(5.0)
...            boxShadow: BoxShadow(MaterialColor(primary value: Color(0xffffeb3b)), Offset(10.0, 10.0), 10.0, 0.0)
...          configuration: ImageConfiguration(bundle: PlatformAssetBundle#589c7(), devicePixelRatio: 1.0, locale: en_US, textDirection: TextDirection.ltr, platform: windows)

**Comment by nabil6391** [comment]
This should be fixed now
