### ISSUE TITLE
Graph so big nothing is visible unless zooming out, centering around `Layout.setFocusedNode` could be a fix

### ISSUE THREAD

**Issue by claudiu-bele** [nabil6391/graphview#33]
Made a video of how the graph looks: https://youtu.be/-oLNpC1voJs

You can see that the top left corner of the graph view (where the graph view seems to always start) is empty, often with every nodes and edge off-screen. 

I had to zoom out alot to be able to start seeing some graph data. If we could "focus" on the focusedNode we'd guarantee that this wouldn't happen.

Any other suggestions on making this work so it doesn't look to the user as though there is no graph?

**Comment by claudiu-bele** [comment]
Alternatively, can we force the zoom to `minFactor` somehow to show the entire graph? Or update the position at runtime based on `selectNode`'s position?

**Comment by shreyasparbat** [comment]
+1. Getting the exact same issue 
![image](https://user-images.githubusercontent.com/31924342/117397477-d4e3fe00-af2e-11eb-8ee7-2cd53d9309c1.png)

**Comment by nabil6391** [comment]
Hi Guys, yes that was the purpose of focsuedNode, However I did not get time to finish the concept, so as of yet its not possible

**Comment by michaeldwu** [comment]
Alternatively, shortening the edge length would help tremendously too.

**Comment by nabil6391** [comment]
Follow #47 for further discussion
