### ISSUE TITLE
Update paint without updating graphView

### ISSUE THREAD

**Issue by pro100svitlo** [nabil6391/graphview#35]
Hello!

Is there a way to update the color of the pain without refreshing the whole `GraphView`?
Right now when I need to highlight some _flow_ - I remove all nodes and all edges and add a new one with proper **pain**.

But it would be nice to add some possibility to refresh color (maybe the node itself as well) without full recreation.
It probably might be achievable with the `builder` method.

**Comment by nabil6391** [comment]
Hi, Which algorithm are you using? I think this should already be possible setState, after changing the edges paint

**Comment by pro100svitlo** [comment]
thanks, it works.
