### ISSUE TITLE
Issue with SugiyamaAlgorithm when introducing circular dependency between nodes

### ISSUE THREAD

**Issue by shreyasparbat** [nabil6391/graphview#38]
Not sure if this is related to the circular dependency, but I've only seen this issue occur in such scenarios. I had two nodes _FTA_ and _EFTA_, with _FTA_ pointing to _EFTA_. When I added a new node _% Auto Accept Bookings_, the edge was not rendered correctly (as can be seen in the image below).

No exceptions or errors were thrown

![image](https://user-images.githubusercontent.com/31924342/117628931-3a90ee00-b1ac-11eb-8cea-a9feb7282c1a.png)

**Comment by nabil6391** [comment]
What should the correct Ui look like?
