### ISSUE TITLE
1.0.0.-nullsafety - Keys aren't being recorded

### ISSUE THREAD

**Issue by JohnGalt1717** [nabil6391/graphview#39]
Take:

  Node getNode(ContentGraphDto content) {
    return Node(
      InkWell(
        child: Container(
          height: 150,
          width: 250,
          child: Text(content.name),
        ),
      ),
      key: ObjectKey(content),
    );
  }
  
  when inspecting the result of this function, you'll note that the key is ValueKey with a number in it and not the objectkey that was passed.

**Comment by nabil6391** [comment]
This way is now deprecated. Please use Node.Id()
