### ISSUE TITLE
How to add a directed edge in Tree graph?

### ISSUE THREAD

**Issue by TimeLord2010** [nabil6391/graphview#42]
I would like to add a directed edge in a tree graph using Buchheim Walker algorithm.

This would be just a standard tree but with directed edges. Is it possible? If so, can a example be provided?

I tried to change the line:
`algorithm: BuchheimWalkerAlgorithm(builder, TreeEdgeRenderer(builder)),`
for:
`algorithm: FruchtermanReingoldAlgorithm(),`

and it kinda worked, except that it lost the rectangular edges.

**Comment by nabil6391** [comment]
Hm the edge rendering cannot be rectangular for FruchtermanReingoldAlgorithm

I am not sure what you mean a standard tree with directed edges.... maybe you can explain to me with a photo?
