### ISSUE TITLE
Not able to connect from 2 node to 1 node

### ISSUE THREAD

**Issue by naaf-44** [nabil6391/graphview#49]
I tried to build a graph for family tree, requirement is from father and mother i need to conenct to child(2 node to 1) using BuchheimWalkerConfiguration  algorith, but I'm not able to connect like that.

**Comment by VengaiMovan** [comment]
Hi @naaf-44 did you find the answer,?

**Comment by naaf-44** [comment]
Not yet sir I'm stuck in that, do you know any way for that

**Comment by VengaiMovan** [comment]
No, I'm also stuck on that. If you find any solution please inform.

**Comment by naaf-44** [comment]
ok

**Comment by nabil6391** [comment]
Keeping issue #51 open , thus closing this
