### ISSUE TITLE
Add a feature to see the all nodes

### ISSUE THREAD

**Issue by JosePedroNobre** [nabil6391/graphview#5]
Allow the user to see the all nodes to allow him to have a perpective of everything. I am having this issue where I can't zoom out more.

<img width="424" alt="Screenshot 2020-09-11 at 22 49 58" src="https://user-images.githubusercontent.com/41454761/92975852-1f38dc00-f481-11ea-8ea8-60c1ecf29e4d.png">

**Comment by nabil6391** [comment]
Released 0.6.1 to fix the problem.

**Comment by JosePedroNobre** [comment]
What should I change for this to happen? @nabil6391

**Comment by nabil6391** [comment]
See the updated example from TreeViewPage.dart
