### ISSUE TITLE
Builder with ID

### ISSUE THREAD

**Issue by vin-fandemand** [nabil6391/graphview#50]
`Node* getNodeUsingId(int* id)` expects an `int id` vs `(new) Node* Node.Id(dynamic id)` expects `dynamic`. Making it dynamic would let us use even a string as an id for the node. Can you please fix this discrepancy?  Also, when will this version be available in null safety.

**Comment by nabil6391** [comment]
You are correct. let me see if I can get some time to work on this

**Comment by nabil6391** [comment]
This is now fixed in 1.0.0
