### ISSUE TITLE
The jank 

### ISSUE THREAD

**Issue by haishuangsu** [nabil6391/graphview#55]
Hey buddy,when my data list more than 100,i find a jank frame. BuchheimWalkerAlgorithm run() takes 700+ ms, how can i solve this problem, thx

![jank](https://user-images.githubusercontent.com/7436804/137361840-4e72b784-b22c-49c7-86b3-0a9244c9c41d.png)

**Comment by stefanschaller** [comment]
I have the same issue. A fix would be great.. At least a proposal to fix it. I could also fix it and create a PR.

**Comment by nabil6391** [comment]
I wish I could help, but the entire foundation might need to be changed.

**Comment by JulianBissekkou** [comment]
Can you explain what you mean by that? What are the flaws of this foundation and how can we improve this?

**Comment by JulianBissekkou** [comment]
I quickly looked into the Issue and it looks like that `nodeOrdering` using your median heuristic is taking too much time.
I would love to chat with you about potential fixes that I can implement and add a pull request.

**Comment by nabil6391** [comment]
Thanks for the call @JulianBissekkou . Appreciate it

**Comment by JulianBissekkou** [comment]
I did some more research and tried to fix the performance by myself, but I think I need some help here.
You can check out #56

**Comment by nabil6391** [comment]
@haishuangsu try updating to 1.1.1. It has some performance improvements for Buchheim Walker
