### ISSUE TITLE
Improve performance of `SugiyamaAlgorithm`

### ISSUE THREAD

**Issue by JulianBissekkou** [nabil6391/graphview#56]
Thanks again for taking the time to hop on a call with me and discuss potential performance fixes.
I reduced the iterations in `nodeOrdering` to 3 and then I did some research to see what else takes the most time.

![image](https://user-images.githubusercontent.com/36447137/142239373-07efc18e-af83-424a-9e18-387e60472d30.png)

As you can see `crossingb` and `assignX` takes most of the time.
I checked the graphview android lib to see if they made any performance adjustments, but there are none.

I tried to optimize both methods but I don't have enough knowledge about the algorithm so I need some help here.
@nabil6391 It would be a help if you could explain what the implementation exactly does and how a fix could look like so I can help.

**Comment by JulianBissekkou** [comment]
I found some performance optimizations in this paper. Might be interesting.

https://jgaa.info/accepted/2005/EiglspergerSiebenhallerKaufmann2005.9.3.pdf

**Comment by nabil6391** [comment]
Thanks for the PR, I will publish to pub.dev soon. 

I have also started looking into the New Algorithm you shared.

**Comment by JulianBissekkou** [comment]
Did you make any progress?

**Comment by nabil6391** [comment]
I am about 30% with the new EiglspergerAlgorithm

**Comment by nabil6391** [comment]
@JulianBissekkou Highly suggest you to update to 1.1.0. There are some major improvements to Sugiyama Algorithm. Do have a look

**Comment by JulianBissekkou** [comment]
Thanks! Improvements are looking really good, but we saw some nodes that are overlapping horizontally.
![image](https://user-images.githubusercontent.com/36447137/145759796-8e824b90-206e-4435-b50a-a93015aa7fdd.png)


I exported the tree as JSON so you can easily reproduce this issue.
here the json: https://gist.github.com/JulianBissekkou/9e2a6a7dccb437b0e781352f7665b99d

**Comment by JulianBissekkou** [comment]
Thanks a lot. If you need any help then let me know :)

**Comment by JulianBissekkou** [comment]
Any luck with the bugfix? @nabil6391

**Comment by nabil6391** [comment]
@JulianBissekkou try out 1.1.1. Should be ok now but let me know if there are any other issues or not

**Comment by JulianBissekkou** [comment]
@nabil6391 I checked out 1.1.1 and I found some overlapping issues. I also added some tests that are failing so you have some data to work with.
You can find that data in my PR #63 

If you need some more details let me know. I can also improve the test suite to include more examples and details.

**Comment by nabil6391** [comment]
Thanks for the tests, I had a brief look. looks like the issues is not with the new code as the tests failed for Old Sugiyama Algorithm as well. I will have to dig deeper to see how to fix that.

**Comment by JulianBissekkou** [comment]
I went through the sources of the java lib and found no change that would be a potential bugfix. Maybe you can take a look as well.
The java lib has a few issues about overlapping that are still open. I send an E-Mail to the maintainers of that lib. Let's see if they fix this issue then we can add the fix to your lib as well.

It would still be good if you can analyze the problem because I don't know if and when they are going to respond.

**Comment by JulianBissekkou** [comment]
@nabil6391 
Did you have the time to check into that issue?

**Comment by nabil6391** [comment]
I did sat one day, found the place which should have taken into account the width (placeBlockWidth)  but could not solve it yet

**Comment by CicadaCinema** [comment]
I was able to produce a minimal test case for the overlapping issue:
```dart
var json = {
  'edges': [
    {'from': '1', 'to': '2'},
    {'from': '1', 'to': '3'},
    {'from': '4', 'to': '7'},
    {'from': '4', 'to': '5'},
    {'from': '9', 'to': '6'},
    {'from': '6', 'to': '4'},
    {'from': '8', 'to': '1'},
  ],
};
```

(substitute in place of the following)
https://github.com/nabil6391/graphview/blob/d7da2d8862d67205c3ab7e95f66e5bf218720fd2/example/lib/layer_graphview_json.dart#L10

**Comment by CicadaCinema** [comment]
Pinging @nabil6391 @JulianBissekkou

**Comment by nabil6391** [comment]
Try out 1.2.0 , fixed overlapping nodes and the tests are not failing as well
