### ISSUE TITLE
how to let the graph scroll while has more nodes,but not zoom

### ISSUE THREAD

**Issue by xiaobingcaicai** [nabil6391/graphview#58]
i dont want to let the graph zoom small,but want to the graph can scrool left to right,or top to bottom while i have lots of nodes to show,how can i do it?

**Comment by xiaobingcaicai** [comment]
my node size is fixed(like 100 * 100),and when i have more node,the graph will not show some nodes

**Comment by nabil6391** [comment]
https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html


You can set scaleEnabled to false in InteractiveViewer to disable zoom

**Comment by xiaobingcaicai** [comment]
> https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html
> 
> You can set scaleEnabled to false in InteractiveViewer to disable zoom

but can not show all my node widget ,and i also can not scroll to display the nodes that be hided

**Comment by xiaobingcaicai** [comment]
> https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html
> 
> You can set scaleEnabled to false in InteractiveViewer to disable zoom

i can show all my node ,but when i control node to center in this way https://github.com/nabil6391/graphview/issues/24#issuecomment-778092126,
if i show tree center, i can not show all node,
if i can show all node,i can not show the tree center

**Comment by nabil6391** [comment]
maybe can try the approach mentioned in #47
