### ISSUE TITLE
When I add paint value nothing is changed 

### ISSUE THREAD

**Issue by Eng-MohamedGadala** [nabil6391/graphview#6]
When I add paint value nothing is changed  stil defult color paint is Black 
` paint: Paint()
                    ..color = Colors.green
                    ..strokeWidth = 1
                    ..style = PaintingStyle.stroke,`

**Comment by nabil6391** [comment]
Which EdgeRenderer are you using? and which algorithm

**Comment by Eng-MohamedGadala** [comment]
@nabil6391 Thanks for fast response 
I'm using BuchheimWalkerAlgorithm as algorithm like images its work fine but can't change path  colors
![Screen Shot 2020-09-17 at 7 57 27 AM](https://user-images.githubusercontent.com/6634311/93426483-6c231500-f8bc-11ea-865b-61bcf46129b0.png)
![Screen Shot 2020-09-17 at 7 58 01 AM](https://user-images.githubusercontent.com/6634311/93426487-6e856f00-f8bc-11ea-9f3a-da959d202c76.png)
![Screen Shot 2020-09-17 at 7 58 31 AM](https://user-images.githubusercontent.com/6634311/93426488-6f1e0580-f8bc-11ea-89cc-3f7a400442ce.png)

**Comment by zhangxinagjunHJH** [comment]
Same problem!

**Comment by nabil6391** [comment]
Released 0.6.1 to fix the problem, thanks for finding it out
