### ISSUE TITLE
Type conversion error in lib/Graph.dart

### ISSUE THREAD

**Issue by MehulDokania** [nabil6391/graphview#60]
Hello. I tried using this package on flutter 2.2.3. I am getting this error 
"A value of type 'dynamic' can't be returned from the function 'hashCode' because it has a return type of 'int'.dart(return_of_invalid_type)"
on line 210 of lib/Graph.dart.
`@override`
  `int?? get hashCode => key?.hashCode ?? Object.hash(source, destination);`
Not sure how to fix this.
Thanks for all the work for creating this package on flutter, exactly what I was looking for!

**Comment by nabil6391** [comment]
You might have to update flutter version.
