### ISSUE TITLE
Method not found: 'Object.hash'

### ISSUE THREAD

**Issue by vin-fandemand** [nabil6391/graphview#73]
![image](https://user-images.githubusercontent.com/64597233/154723149-104dd6f1-dd38-4b2b-bfe9-90cd391218df.png)
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (9 months ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

graphview: ^1.1.1

**Comment by nabil6391** [comment]
Please update your flutter version to 2.6.0 min
