### ISSUE TITLE
edit the color of just some nodes, how I can do it?

### ISSUE THREAD

**Issue by flutter87** [nabil6391/graphview#77]
MY CODE
class _TreeViewPageFromJsonState extends State<TreeViewPageFromJson> {
  var json = {
    'nodes': [
      {'id': 1, 'label': 'circle'},
      {'id': 2, 'label': 'ellipse'},
      {'id': 3, 'label': 'database'},
    ],
    'edges': [
      {'from': 1, 'to': 2},
      {'from': 2, 'to': 3},
      {'from': 1, 'to': 3},
    ]
  };
.....
              child: InteractiveViewer(
              ....
                  child: GraphView(
                    graph: graph,
                    algorithm: BuchheimWalkerAlgorithm(builder, TreeEdgeRenderer(builder)),
                    paint: Paint()          
                    builder: (Node node) {
                      var a = node.key!.value as int?;
                      var nodes = json['nodes']!;
                      var nodeValue = nodes.firstWhere((element) => element['id'] == a);
                      return rectangleWidget(nodeValue['label'] as String?);
          ....

  Widget rectangleWidget(String? a) {
    return Container(
          child: Text('${a}')),
    );
  }

  final Graph graph = Graph()..isTree = true;
  BuchheimWalkerConfiguration builder = BuchheimWalkerConfiguration();

  @override
  void initState() {
    var edges = json['edges']!;
    edges.forEach((element) {
      var fromNodeId = element['from'];
      var toNodeId = element['to'];
      graph.addEdge(Node.Id(fromNodeId), Node.Id(toNodeId));
    });

**Comment by nabil6391** [comment]
you can pass the color as a parameter to the rectangleWidget

**Comment by NehaKushwah993** [comment]
rectangleWidget() is providing the node, you can change it from there.
