### ISSUE TITLE
Use BuchheimWalkerConfiguration to show tree merge node has problem

### ISSUE THREAD

**Issue by zhangxinagjunHJH** [nabil6391/graphview#8]
### I use BuchheimWalkerConfiguration like this, there are 2 branch and one merge node, it's OK
`graph.addEdge(node1, node2, paint: Paint()..color = Colors.red);
graph.addEdge(node2, node6);
graph.addEdge(node6, node5);

graph.addEdge(node2, node3);
graph.addEdge(node3, node4);
graph.addEdge(node4, node5);`
![image](https://user-images.githubusercontent.com/11606130/94142155-6622ca80-fea0-11ea-93ce-8ecdbffd9446.png)

 
### but if i change the order like this, it will show wrong connect line
`graph.addEdge(node1, node2, paint: Paint()..color = Colors.red);
graph.addEdge(node2, node3);
graph.addEdge(node3, node4);
graph.addEdge(node4, node5);

graph.addEdge(node2, node6);
graph.addEdge(node6, node5);`
![image](https://user-images.githubusercontent.com/11606130/94142164-69b65180-fea0-11ea-96ac-adfbf4905f01.png)

**Comment by nabil6391** [comment]
Basically  BuchheimWalker is for treelayouts only, if you want merged nodes, suggest you use Sugiyama

**Comment by zhangxinagjunHJH** [comment]
@nabil6391 Yes, I checked code both Sugiyama and  FruchtermanReingoldAlgorithm, but i found they don't support change  orientation to horizontal. can add this feature to them?

**Comment by nabil6391** [comment]
Hm that is correct, yes I would prefer to add them but do not think it can be done soon.

**Comment by zhangxinagjunHJH** [comment]
@nabil6391 OK, Thank you very much! I will continue to pay attention and wait.

**Comment by nabil6391** [comment]
Added support for different orientation in 0.6.5. Try it out. Closing for now.
