### ISSUE TITLE
Is it possible to position leaf nodes on the same level?

### ISSUE THREAD

**Issue by mway-niels** [nabil6391/graphview#86]
Hello,

I am using graphview to create an organization chart for my company. I am now wondering if it is possible to position all leaf nodes (in my case individual teams) at the same level, regardless of how long the chain of managers above the team is.

I have considered (but not yet tested) using virtual nodes between the team and the manager to move the leaf node down X levels. Is there a better solution to my problem?

I have created a diagram to illustrate my goal:

Current:
<img width="919" alt="Screenshot 2022-07-21 at 10 55 51" src="https://user-images.githubusercontent.com/53857383/180173751-f4b42221-208b-4d25-b7b0-b836b16808a2.png">

Target:
<img width="935" alt="Screenshot 2022-07-21 at 10 56 10" src="https://user-images.githubusercontent.com/53857383/180173773-b1b40af6-3466-4ae1-81ec-a82207c4ccc9.png">

**Comment by jayaxel** [comment]
try this:
Flip the source and target, AND set orientation as ORIENTATION_BOTTOM_TOP

i found this while trying to reverse the arrows with no avail. you can see an illustration in my reported issue:
https://github.com/nabil6391/graphview/issues/72

**Comment by nabil6391** [comment]
Try out 1.2.0 , added a new CoordinateAssignment to allow users to adjust alignment
