### ISSUE TITLE
Nodes overlap in complex graphs

### ISSUE THREAD

**Issue by lmis-frontend** [nabil6391/graphview#87]
![Bildschirmfoto 2022-08-03 um 10 29 54](https://user-images.githubusercontent.com/98831574/182566054-3a179c18-2fbe-42db-a97e-e42b3eb16407.png)

Hello,
We use the plugin (graphview: ^1.1.1) with the Sugiyama algorithm. In more complex graphs, the individual nodes often overlap. As can be seen in the attached image, each branch is followed by a green and a red path. However, in the marked area, the red and green paths overlap.

Do you know what could cause this problem and how to fix it?

**Comment by lakharasachin-qf** [comment]
I m facing the same issue. when graph goes more with 2,3 level depth nodes are overlapping randomly

**Comment by CicadaCinema** [comment]
There is some relevant discussion in the following issue regarding overlapping nodes with the Sugiyama algorithm: https://github.com/nabil6391/graphview/issues/56

**Comment by nabil6391** [comment]
Yeah this had been a problem.  I will try to investigate more

**Comment by lakharasachin-qf** [comment]
> I will try to investigate more

Hello @nabil6391 
did you find out any solution for overlapping issue.??

**Comment by tabrezcool6** [comment]
Hello @nabil6391 , 
Did you find any solution for the overlapping of the nodes...

**Comment by nabil6391** [comment]
Fixed in 1.2.0 , please try and let me know
