### ISSUE TITLE
Is it possible to export the graph to PDF ?

### ISSUE THREAD

**Issue by sulfy** [nabil6391/graphview#89]
I tried this amazing package for my flutter family tree project, now I am facing an issue that I can't see my whole family tree in a single window. 

* Can I export the graph to pdf ?
* or can I fit the whole graph on my large screen? so that I can take a screenshot ?
* print to pdf is not working as it only prints the visible area

please help

**Comment by lakharasachin-qf** [comment]
same problem, please help I want to export my family tree graph to pdf

**Comment by nabil6391** [comment]
Use Repaint Boundary:

https://medium.com/flutter-community/export-your-widget-to-image-with-flutter-dc7ecfa6bafb
