### ISSUE TITLE
I m facing the same issue. when graph goes more with 2,3 level depth nodes are overlapping randomly

### ISSUE THREAD

**Issue by lakharasachin-qf** [nabil6391/graphview#93]
I m facing the same issue. when graph goes more with 2,3 level depth nodes are overlapping randomly

_Originally posted by @lakharasachin-qf in https://github.com/nabil6391/graphview/issues/87#issuecomment-1277516299_

**Comment by CicadaCinema** [comment]
There is some relevant discussion in the following issue regarding overlapping nodes with the Sugiyama algorithm: https://github.com/nabil6391/graphview/issues/56

**Comment by lakharasachin-qf** [comment]
> 

thanks that issue is resolve now.
But now there is an another issue I m facing please take a look on #96
