### ISSUE TITLE
Why In SugiyamaAlgorithm nodes are aligned with top when tree depth is unbalanced 

### ISSUE THREAD

**Issue by lakharasachin-qf** [nabil6391/graphview#96]
![0414DA52-D30A-4937-9CF3-A60DDB58DEB1_1_201_a](https://user-images.githubusercontent.com/62238022/204088764-0bea142b-73b0-4139-b792-ab820d630f76.jpeg)

Why Node 1 is not in the same level of node 2. But when i add 3 more on top of node 1 then it will comes on the same level of Node 2.

Please help to figure this out...

**Comment by nabil6391** [comment]
i will take a look at this, can you help export this data so that i can test

**Comment by lakharasachin-qf** [comment]
> i will take a look at this, can you help export this data so that i can test

I had change the file "SugiyamaEdgeRenderer.dart" as per my requirement

**Comment by lakharasachin-qf** [comment]
> i will take a look at this, can you help export this data so that i can test

@nabil6391  did you get time to take a look on the issue

**Comment by nabil6391** [comment]
Try out 1.2.0 , added a new CoordinateAssignment to allow users to adjust alignment
